name: EHA-mayflower
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - mamba
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pillow
  - tqdm
  - networkx
  - sympy
  - pip